routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('password', function(){
	return Hash::make('qwerty');  
});
Route::get('/', 'AuthController@index')->name('index');
Auth::routes(['register' => false]);

Route::group(['middleware' => ['session']], function () {

	Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
	Route::get('metode', 'HomeController@metode')->name('metode');
	Route::post('fuzzy', 'HomeController@fuzzy')->name('fuzzy');

	Route::resource('users', 'UserController');
	Route::get('users/delete/{id}', 'UserController@delete');

	Route::resource('warung', 'WarungController');
	Route::get('warung/delete/{id}', 'WarungController@delete');

	Route::resource('meja', 'MejaController');
	Route::get('meja/delete/{id}', 'MejaController@delete');

	// Route::resource('menu', 'MenuController');
	Route::get('menu/delete/{id}/{warung_id}', 'MenuController@delete');
	Route::get('menu/{warung_id}/create', 'MenuController@create_menu');
	Route::get('menu/{id}', 'MenuController@show');
	Route::get('menu/{id}/edit', 'MenuController@edit');
	Route::post('menu/update/{id}', 'MenuController@update');
	Route::post('menu/store', 'MenuController@store');

	Route::resource('report', 'ReportController');

	Route::get('order', 'OrderController@index');
	Route::get('order/create', 'OrderController@create');
	Route::post('order/store', 'OrderController@post_create');
	Route::get('order/detail/{id}', 'OrderController@detail');
	Route::get('order/delete/{id}', 'OrderController@delete');
	Route::get('order/approve/{id}', 'OrderController@approve');


});
// Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\UserDataTable;
use App\User;
use App\Warung;
use Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserDataTable $dataTable)
    {
        return $dataTable->render('user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $warung = Warung::all();
        return view('user.create',compact('warung'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (User::where('username',$request->username)->count() > 0) {
            return redirect()->back()->with('alert-warning','Username sudah digunakan silahkan coba yang lain');
        }

        if (User::where('warung_id',$request->warung_id)->count() > 0) {
            return redirect()->back()->with('alert-warning','Data tidak boleh sama');
        }

        $user = new User;
        if (!empty($request->warung_id)) {
            $user->warung_id    = $request->warung_id;
        }
        $user->name         = $request->name;
        $user->email        = $request->email;
        $user->username     = $request->username;
        $user->password     = Hash::make($request->password);
        $user->type         = $request->type;
        $user->save();

        return redirect('users')->with('alert-success','Berhasil update data');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('user.update',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (User::where('id','!=',$id)->where('username',$request->username)->count() > 0) {
            return redirect()->back()->with('alert-warning','Username sudah digunakan silahkan coba yang lain');
        }

        $user = User::findOrFail($id);
        $user->name         = $request->name;
        $user->email        = $request->email;
        $user->username     = $request->username;
        if (!empty($request->password)) {
            $user->password     = Hash::make($request->password);
        }
        $user->type         = $request->type;
        $user->save();

        return redirect('users')->with('alert-success','Berhasil update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function delete($id)
    {
        User::findOrFail($id)->delete();
        return redirect('users')->with('alert-success','Success deleted data');
    }
}

resources/views/user/create.blade.php
@extends('layouts.master')
@section('title','Add New User')
@section('css')

@endsection
@section('content')
<section class="content-header">
  <h1>Master User</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="{{route('users.index')}}"> User</a></li>
    <li class="active">Add New User</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add New User</h3>
            </div>
            <div class="">
            	<form role="form" action="{{route('users.store')}}" method="POST">
	            	{{csrf_field()}}
	              	<div class="box-body">
		                <div class="form-group">
		                  <label>Name</label>
		                  <input type="text" required name="name" required class="form-control">
		                </div>
                    <div class="form-group">
                      <label>Email</label>
                      <input type="email" required name="email" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Username</label>
                      <input type="text" required name="username" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Password</label>
                      <input type="password" required name="password" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Type User</label>
                      <select name="type" required class="form-control type" id="">
                        <option value="">-</option>
                        <option value="warung">Admin Warung</option>
                        {{-- <option value="pusat">Admin Pusat</option> --}}
                        <option value="admin">SuperAdmin</option>
                        <option value="kasir">Kasir</option>
                      </select>
                    </div>
                    <div class="form-group form-warung" style="display: none;">
                      <label>Pilih Warung</label>
                      <select name="warung_id" disabled class="form-control warung" style="display: none;">
                        @foreach($warung as $dat_warung)
                        <option value="{{$dat_warung->id}}">{{$dat_warung->nama}}</option>
                        @endforeach
                      </select>
                    </div>
	              	</div>
	              	<div class="box-footer">
		                <a href="{{route('users.index')}}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
		                <button class="btn btn-primary"><i class="fa fa-save"></i> Next</button>
	              	</div>
	            </form>
            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')
<script>
  $('.type').change(function(){
    if($(this).val() == 'warung'){
      $('.form-warung').show();
      $('.warung').show();
      $('.warung').removeAttr('disabled');
    }else{
      $('.form-warung').hide();
      $('.warung').hide();
      $('.warung').attr('disabled',true);
    }
  });
</script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title','Management User')
@section('css')
<link rel="stylesheet" href="{{asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/bower_components/datatables.net-bs/css/dataTables-button.css')}}">
@endsection
@section('content')
<section class="content-header">
  <h1>Data User</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Data User</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box">
	            <div class="box-body">
	            	<div class="table-responsive">
	            		{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
	            	</div>
	            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')
<script src="{{asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/dataTables-button.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/button-server.js')}}"></script>
{!! $dataTable->scripts() !!}
<script>
	$(document).ready(function(){
		$("#user-table").on("click", ".remove_data", function () {
			var url = $(this).attr('data-href');
	        swal({
	            title: "Are You Sure ?",
	            text: "Delete this data cannot be restore",
	            type: "warning",
	            showCancelButton: true,
	            confirmButtonColor: "#DD6B55",
	            confirmButtonText: "YES",
	            cancelButtonText: "NO",
	            closeOnConfirm: true,
	            closeOnCancel: true
	          },
	          function(isConfirm){
	            if (isConfirm) {
	              document.location.href = url;
	            }
	          });

	        return false;
		});
	});
</script>
@endsection

resources/views/user/update.blade.php
@extends('layouts.master')
@section('title','Update User')
@section('css')

@endsection
@section('content')
<section class="content-header">
  <h1>Master User</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="{{route('users.index')}}"> User</a></li>
    <li class="active">Update User</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Update User</h3>
            </div>
            <div class="">
            	<form role="form" action="{{route('users.update',$user->id)}}" method="POST">
	            	{{csrf_field()}}
                @method('PUT')
	              	<div class="box-body">
                    <div class="form-group">
                      <label>Name</label>
                      <input type="text" required name="name" value="{{$user->name}}" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Email</label>
                      <input type="email" required name="email" value="{{$user->email}}" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Username</label>
                      <input type="text" required name="username" value="{{$user->username}}" required class="form-control">
                    </div>
                    <div class="form-group">
                      <label>New Password</label>
                      <input type="password" name="password" class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Type User</label>
                      <select name="type" required class="form-control" id="">
                        <option @if($user->type == 'warung') selected @endif value="warung">Admin Warung</option>
                        <option @if($user->type == 'pusat') selected @endif value="pusat">Admin Pusat</option>
                        <option @if($user->type == 'admin') selected @endif value="admin">SuperAdmin</option>
                      </select>
                    </div>
                  </div>
	              	<div class="box-footer">
		                <a href="{{route('users.index')}}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
		                <button class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
	              	</div>
	            </form>
            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')

@endsection