routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('password', function(){
	return Hash::make('qwerty');  
});
Route::get('/', 'AuthController@index')->name('index');
Auth::routes(['register' => false]);

Route::group(['middleware' => ['session']], function () {

	Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
	Route::get('metode', 'HomeController@metode')->name('metode');
	Route::post('fuzzy', 'HomeController@fuzzy')->name('fuzzy');

	Route::resource('users', 'UserController');
	Route::get('users/delete/{id}', 'UserController@delete');

	Route::resource('warung', 'WarungController');
	Route::get('warung/delete/{id}', 'WarungController@delete');

	Route::resource('meja', 'MejaController');
	Route::get('meja/delete/{id}', 'MejaController@delete');

	// Route::resource('menu', 'MenuController');
	Route::get('menu/delete/{id}/{warung_id}', 'MenuController@delete');
	Route::get('menu/{warung_id}/create', 'MenuController@create_menu');
	Route::get('menu/{id}', 'MenuController@show');
	Route::get('menu/{id}/edit', 'MenuController@edit');
	Route::post('menu/update/{id}', 'MenuController@update');
	Route::post('menu/store', 'MenuController@store');

	Route::resource('report', 'ReportController');

	Route::get('order', 'OrderController@index');
	Route::get('order/create', 'OrderController@create');
	Route::post('order/store', 'OrderController@post_create');
	Route::get('order/detail/{id}', 'OrderController@detail');
	Route::get('order/delete/{id}', 'OrderController@delete');
	Route::get('order/approve/{id}', 'OrderController@approve');


});
// Route::get('/home', 'HomeController@index')->name('home');

resources/views/include/alert.blade.php
@if(Session::has('alert-success'))
    <div class="alert alert-success alert-dismissible" role="alert">
	  {{Session::get('alert-success')}}
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	</div>
@elseif(Session::has('alert-danger'))
    <div class="alert alert-danger alert-dismissible" role="alert">
	  {{Session::get('alert-danger')}}
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	</div>
@elseif(Session::has('alert-warning'))
    <div class="alert alert-warning alert-dismissible" role="alert">
	  {{Session::get('alert-warning')}}
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	</div>
@endif

resources/views/include/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>HS</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Hangout Salihara</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </nav>
</header>

resources/views/include/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li @if(Request::is('dashboard')) class="active" @endif>
        <a href="{{url('dashboard')}}">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>
      @if((Auth::user()->type == 'admin') || (Auth::user()->type == 'warung'))
      <li @if(Request::is('order*')) class="active" @endif>
        <a href="{{url('order')}}">
          <i class="fa fa-calculator"></i> <span> Pesanan</span>
        </a>
      </li>
      @endif
      @if(Auth::user()->type == 'admin')
      <li @if(Request::is('warung*')) class="active" @endif>
        <a href="{{route('warung.index')}}">
          <i class="fa fa-home"></i> <span> Warung</span>
        </a>
      </li>
      <li @if(Request::is('meja*')) class="active" @endif>
        <a href="{{route('meja.index')}}">
          <i class="fa fa-table"></i> <span> Meja</span>
        </a>
      </li>
      <li @if(Request::is('metode*')) class="active" @endif>
        <a href="{{url('metode')}}">
          <i class="fa fa-line-chart"></i> <span> Metode</span>
        </a>
      </li>
      <li @if(Request::is('users*')) class="active" @endif>
        <a href="{{route('users.index')}}">
          <i class="fa fa-group"></i> <span> Management User</span>
        </a>
      </li>
      @endif
      <li @if(Request::is('report*')) class="active" @endif>
        <a href="{{route('report.index')}}">
          <i class="fa fa-database"></i> <span> Report</span>
        </a>
      </li>
      <li>
        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
          <i class="fa fa-sign-out"></i> <span>{{ __('Logout') }}</span>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
        </form>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>