routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('password', function(){
	return Hash::make('qwerty');  
});
Route::get('/', 'AuthController@index')->name('index');
Auth::routes(['register' => false]);

Route::group(['middleware' => ['session']], function () {

	Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
	Route::get('metode', 'HomeController@metode')->name('metode');
	Route::post('fuzzy', 'HomeController@fuzzy')->name('fuzzy');

	Route::resource('users', 'UserController');
	Route::get('users/delete/{id}', 'UserController@delete');

	Route::resource('warung', 'WarungController');
	Route::get('warung/delete/{id}', 'WarungController@delete');

	Route::resource('meja', 'MejaController');
	Route::get('meja/delete/{id}', 'MejaController@delete');

	// Route::resource('menu', 'MenuController');
	Route::get('menu/delete/{id}/{warung_id}', 'MenuController@delete');
	Route::get('menu/{warung_id}/create', 'MenuController@create_menu');
	Route::get('menu/{id}', 'MenuController@show');
	Route::get('menu/{id}/edit', 'MenuController@edit');
	Route::post('menu/update/{id}', 'MenuController@update');
	Route::post('menu/store', 'MenuController@store');

	Route::resource('report', 'ReportController');

	Route::get('order', 'OrderController@index');
	Route::get('order/create', 'OrderController@create');
	Route::post('order/store', 'OrderController@post_create');
	Route::get('order/detail/{id}', 'OrderController@detail');
	Route::get('order/delete/{id}', 'OrderController@delete');
	Route::get('order/approve/{id}', 'OrderController@approve');


});
// Route::get('/home', 'HomeController@index')->name('home');

app/Meja.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meja extends Model
{
    protected $table = 'meja';
}

app/Http/Controllers/MejaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\MejaDataTable;
use App\Meja;

class MejaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(MejaDataTable $dataTable)
    {
        return $dataTable->render('meja.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('meja.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Meja::where('nama',$request->nama)->count() > 0) {
            return redirect()->back()->with('alert-warning','Nama meja sudah digunakan silahkan coba yang lain');
        }

        $meja = new Meja;
        $meja->nama         = $request->nama;
        $meja->save();

        return redirect('meja')->with('alert-success','Berhasil update data');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meja = Meja::findOrFail($id);
        return view('meja.update',compact('meja'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Meja::where('id','!=',$id)->where('nama',$request->nama)->count() > 0) {
            return redirect()->back()->with('alert-warning','Nama meja sudah digunakan silahkan coba yang lain');
        }

        $meja = Meja::findOrFail($id);
        $meja->nama    = $request->nama;
        $meja->save();

        return redirect('meja')->with('alert-success','Berhasil update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function delete($id)
    {
        Meja::findOrFail($id)->delete();
        return redirect('meja')->with('alert-success','Success deleted data');
    }
}

resources/views/meja/create.blade.php
@extends('layouts.master')
@section('title','Add New Meja')
@section('css')

@endsection
@section('content')
<section class="content-header">
  <h1>Master Meja</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="{{route('meja.index')}}"> Meja</a></li>
    <li class="active">Add New Meja</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add New Meja</h3>
            </div>
            <div class="">
            	<form role="form" action="{{route('meja.store')}}" method="POST">
	            	{{csrf_field()}}
	              	<div class="box-body">
		                <div class="form-group">
		                  <label>Nama Meja</label>
		                  <input type="text" required name="nama" required class="form-control">
		                </div>
	              	</div>
	              	<div class="box-footer">
		                <a href="{{route('meja.index')}}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
		                <button class="btn btn-primary"><i class="fa fa-save"></i> Next</button>
	              	</div>
	            </form>
            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')

@endsection

resources/views/meja/index.blade.php
@extends('layouts.master')
@section('title','Meja')
@section('css')
<link rel="stylesheet" href="{{asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/bower_components/datatables.net-bs/css/dataTables-button.css')}}">
@endsection
@section('content')
<section class="content-header">
  <h1>Data Meja</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Data Meja</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box">
	            <div class="box-body">
	            	<div class="table-responsive">
	            		{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
	            	</div>
	            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')
<script src="{{asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/dataTables-button.js')}}"></script>
<script src="{{asset('admin/bower_components/datatables.net-bs/js/button-server.js')}}"></script>
{!! $dataTable->scripts() !!}
<script>
	$(document).ready(function(){
		$("#meja-table").on("click", ".remove_data", function () {
			var url = $(this).attr('data-href');
	        swal({
	            title: "Are You Sure ?",
	            text: "Delete this data cannot be restore",
	            type: "warning",
	            showCancelButton: true,
	            confirmButtonColor: "#DD6B55",
	            confirmButtonText: "YES",
	            cancelButtonText: "NO",
	            closeOnConfirm: true,
	            closeOnCancel: true
	          },
	          function(isConfirm){
	            if (isConfirm) {
	              document.location.href = url;
	            }
	          });

	        return false;
		});
	});
</script>
@endsection

resources/views/meja/update.blade.php
@extends('layouts.master')
@section('title','Update Meja')
@section('css')

@endsection
@section('content')
<section class="content-header">
  <h1>Master Meja</h1>
  <ol class="breadcrumb">
    <li><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="{{route('meja.index')}}"> Meja</a></li>
    <li class="active">Update Meja</li>
  </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			@include('include.alert')
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Update Meja</h3>
            </div>
            <div class="">
            	<form role="form" action="{{route('meja.update',$meja->id)}}" method="POST">
	            	{{csrf_field()}}
                @method('PUT')
	              	<div class="box-body">
                    <div class="form-group">
                      <label>Nama Meja</label>
                      <input type="text" required name="nama" value="{{$meja->nama}}" required class="form-control">
                    </div>
                  </div>
	              	<div class="box-footer">
		                <a href="{{route('meja.index')}}" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
		                <button class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
	              	</div>
	            </form>
            </div>
          </div>
        </div>
    </div>
</section>
@endsection
@section('js')

@endsection